export const GAME_ASSETS_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "admin", type: "address", internalType: "address" },
      { name: "consumer", type: "address", internalType: "address" },
      { name: "initialTreasury", type: "address", internalType: "address" },
      { name: "initialPaymentTokens", type: "address[]", internalType: "address[]" },
      { name: "initialTokenDecimals", type: "uint8[]", internalType: "uint8[]" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CONSUMER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "HINT",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STREAK_FREEZE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DAILY_PASS",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dailyPassDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dailyPassPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasActiveDailyPass",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDailyPassExpiry",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "purchaseDailyPass",
    inputs: [{ name: "paymentToken", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "grantDailyPass",
    inputs: [{ name: "to", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDailyPassPrice",
    inputs: [{ name: "price", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDailyPassDuration",
    inputs: [{ name: "duration", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "PRICE_DECIMALS",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paymentTokens",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPaymentToken",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenDecimals",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "assetPacks",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "name", type: "string" },
      { name: "assetType", type: "bytes32" },
      { name: "quantity", type: "uint256" },
      { name: "price", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balances",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unitPrices",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHintBalance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStreakFreezeBalance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBalance",
    inputs: [
      { name: "user", type: "address" },
      { name: "assetType", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAssetPackCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPaymentTokenCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAssetPack",
    inputs: [{ name: "packId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameAssets.AssetPack",
        components: [
          { name: "name", type: "string" },
          { name: "assetType", type: "bytes32" },
          { name: "quantity", type: "uint256" },
          { name: "price", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllAssetPacks",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct GameAssets.AssetPack[]",
        components: [
          { name: "name", type: "string" },
          { name: "assetType", type: "bytes32" },
          { name: "quantity", type: "uint256" },
          { name: "price", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "purchaseAsset",
    inputs: [
      { name: "assetType", type: "bytes32" },
      { name: "quantity", type: "uint256" },
      { name: "paymentToken", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "purchaseAssetPack",
    inputs: [
      { name: "packId", type: "uint256" },
      { name: "paymentToken", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "grantAsset",
    inputs: [
      { name: "to", type: "address" },
      { name: "assetType", type: "bytes32" },
      { name: "quantity", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "grantAssetPack",
    inputs: [
      { name: "to", type: "address" },
      { name: "packId", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "consumeHint",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "consumeStreakFreeze",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createAssetPack",
    inputs: [
      { name: "name", type: "string" },
      { name: "assetType", type: "bytes32" },
      { name: "quantity", type: "uint256" },
      { name: "price", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateAssetPack",
    inputs: [
      { name: "packId", type: "uint256" },
      { name: "price", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUnitPrice",
    inputs: [
      { name: "assetType", type: "bytes32" },
      { name: "price", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateTreasury",
    inputs: [{ name: "newTreasury", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addPaymentToken",
    inputs: [
      { name: "token", type: "address" },
      { name: "decimals", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removePaymentToken",
    inputs: [{ name: "token", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRoleAdmin",
    inputs: [{ name: "role", type: "bytes32" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceRole",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "callerConfirmation", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeRole",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AssetPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "assetType", type: "bytes32", indexed: true },
      { name: "quantity", type: "uint256", indexed: false },
      { name: "totalPrice", type: "uint256", indexed: false },
      { name: "paymentToken", type: "address", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AssetPackPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "packId", type: "uint256", indexed: true },
      { name: "paymentToken", type: "address", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AssetGranted",
    inputs: [
      { name: "to", type: "address", indexed: true },
      { name: "assetType", type: "bytes32", indexed: true },
      { name: "quantity", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AssetConsumed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "assetType", type: "bytes32", indexed: true },
      { name: "quantity", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AssetPackCreated",
    inputs: [
      { name: "packId", type: "uint256", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "assetType", type: "bytes32", indexed: false },
      { name: "quantity", type: "uint256", indexed: false },
      { name: "price", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AssetPackUpdated",
    inputs: [
      { name: "packId", type: "uint256", indexed: true },
      { name: "price", type: "uint256", indexed: false },
      { name: "active", type: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UnitPriceSet",
    inputs: [
      { name: "assetType", type: "bytes32", indexed: true },
      { name: "price", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TreasuryUpdated",
    inputs: [
      { name: "oldTreasury", type: "address", indexed: false },
      { name: "newTreasury", type: "address", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentTokenAdded",
    inputs: [
      { name: "token", type: "address", indexed: false },
      { name: "decimals", type: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentTokenRemoved",
    inputs: [{ name: "token", type: "address", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "DailyPassPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "expiry", type: "uint256", indexed: false },
      { name: "paymentToken", type: "address", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DailyPassGranted",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "expiry", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DailyPassPriceSet",
    inputs: [{ name: "price", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "DailyPassDurationSet",
    inputs: [{ name: "duration", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      { name: "role", type: "bytes32", indexed: true },
      { name: "previousAdminRole", type: "bytes32", indexed: true },
      { name: "newAdminRole", type: "bytes32", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      { name: "role", type: "bytes32", indexed: true },
      { name: "account", type: "address", indexed: true },
      { name: "sender", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      { name: "role", type: "bytes32", indexed: true },
      { name: "account", type: "address", indexed: true },
      { name: "sender", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AccessControlBadConfirmation",
    inputs: [],
  },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address" },
      { name: "neededRole", type: "bytes32" },
    ],
  },
  {
    type: "error",
    name: "AddressEmptyCode",
    inputs: [{ name: "target", type: "address" }],
  },
  {
    type: "error",
    name: "AddressInsufficientBalance",
    inputs: [{ name: "account", type: "address" }],
  },
  {
    type: "error",
    name: "FailedInnerCall",
    inputs: [],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address" }],
  },
] as const;
