// Re-export from shared contracts package
export {
  GAME_ASSETS_CONTRACT,
  PAYOUT_CLAIM_CONTRACT,
  PAYMENT_RECIPIENT,
  GAME_ASSET_TYPES,
  SUPPORTED_CURRENCIES,
  ALLOWLISTED_STABLECOINS,
  CUSD_ADDRESSES,
} from "@workspace/contracts";
